baseURL = 'http://bugswriter.com'
languageCode = 'en-us'
title = "Suraj Kushwah" 
theme = "bw-hugo-theme"
paginate = 5

[menu]
  [[menu.main]]
  name = "Homepage"
  URL = "/"
  weight = 1
  
[[menu.main]]
  name = "Who am I?"
  URL = "/about"
  weight = 2
  
[[menu.main]]
  name = "Blog and stuff"
  URL = "/blog"
  weight = 3

[[menu.main]]
  name = "Git Server"
  URL = "https://git.bugswriter.com"
  weight = 5

[[menu.main]]
  name = "How to reach me?"
  url = "contact"
  weight = 6
